### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by Gormartsen** [backdrop-contrib/bee#3]
I don't have one.
Somebody please help with bat file to make it work on windows machines. )

**Comment by Gormartsen** [comment]
There are more Windows related issues.
Like table output is looking for screen width by `tput`.

Windows is not supported at all at this point.

I don't have it. 

Probably somebody with Windows can help here out.

**Comment by yorkshire-pudding** [comment]
There appears to be very little demand for this.  As a Windows user myself, I use `bee` within lando on WSL2.  It could also be used natively on WSL/WSL2 or any other virtual machine within Linux.

Changing `bee` to allow it to run natively on Windows would be prohibitively complex and is therefore not a priority.
